### ISSUE TITLE
Pyre confuses a local module and a global module when they have the same name

### ISSUE THREAD

**Issue by dahlia** [facebook/pyre-check#106]
Pyre confuses a local module and a global module when they have the same name.  [Here's source codes to reproduce it][1]:

    git clone \
        git@bitbucket.org:snippets/dahlia/nedBnr/pyre-confuses-a-local-module-and-a-global.git \
        repro
    cd repro/
    pip install pyre-check==0.0.14
    pyre --source-directory testpkg check

The last `pyre` command prints the following result:

    testpkg/a.py:7:4 Undefined attribute [16]: Module `datetime` has no attribute `foo`.

While it is expected to print the below:

    testpkg/a.py:9:4 Undefined attribute [16]: Module `datetime` has no attribute `datetime`.

For more details, please read [*testpkg/a.py*][2] file as well.

[1]: https://bitbucket.org/snippets/dahlia/nedBnr
[2]: https://bitbucket.org/snippets/dahlia/nedBnr#file-testpkg/a.py

**Comment by mrkmndz** [comment]
The key issue here is that setting a source directory interprets the sources contained as if the source directory was the top level for python.  Because python doesn't support `from .foo import bar` at the top level, we don't either.  The problem you described doesn't happen if you run pyre with `--source-directory .`, because we fully qualify `.datetime` to `testpkg.datetime`.  Can I ask why you need to run with `--source-directory testpkg`?

**Comment by mrkmndz** [comment]
If you want to override a built in, you just need to put it in a folder, like `overrides/datetime` and then just `from overrides.datetime import foo`.

**Comment by dahlia** [comment]
Okay, I now understand what `--source-directory` means.  It seems to work well if I give `.` to `--source-directory`.
