### ISSUE TITLE
Not installing on macOS Sierra

### ISSUE THREAD

**Issue by stealthybox** [facebook/pyre-check#11]
macOS Sierra 10.12.6
using python's installed with brew:
```bash
❯ pip3 install pyre-check
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: )
No matching distribution found for pyre-check

❯ pip3.6 install pyre-check
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: )
No matching distribution found for pyre-check

❯ pip2 install pyre-check
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: )
No matching distribution found for pyre-check
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

❯ ll $(which pip3)
lrwxr-xr-x  1 leigh.schrandt  admin    31B Apr 22 00:29 /usr/local/bin/pip3 -> ../Cellar/python/3.6.5/bin/pip3

❯ ll $(which pip2)
lrwxr-xr-x  1 leigh.schrandt  admin    36B Apr 23 15:47 /usr/local/bin/pip2 -> ../Cellar/python@2/2.7.14_3/bin/pip2
```
similar to #5

**Comment by stealthybox** [comment]
re: @DanielCollins
cc: @dgki @dark

other reports: https://news.ycombinator.com/item?id=17049415

**Comment by dkgi** [comment]
I suspect this is us not shipping OCaml binaries for those platforms. What architecture are you running this on?

**Comment by dark** [comment]
We're currently tagging all macOS releases of `pyre-check` to run on >= 10.13 because:
* that's where I am compiling the binaries and testing them on;
* given my limited experience with the Mach-O format, I assumed that from the output of `otool -l pyre.bin` we could only run on 10.13:
```
[...]
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 10.13
[...]
```

The output of `pip3.6 install pyre-check --verbose` would confirm that indeed pip is skipping macOS 10.12 only due to the version requirement. @stealthybox could you please provide that?

I will investigate `LC_VERSION_MIN_MACOSX` more to see if this is a strict requirement or not.

**Comment by DanielCollins** [comment]
https://gist.github.com/DanielCollins/629ae4cd2c0fb5a594b9edc1048045ca

**Comment by stealthybox** [comment]
@dark I'm getting the same output as @DanielCollins

**Comment by mingrammer** [comment]
I have same problem on macOS Sierra

**Comment by dark** [comment]
Messing around with `MACOSX_DEPLOYMENT_TARGET` yields the expected result. The entire toolchain (i.e. including `~/.opam`) needs a rebuild.

**Comment by dark** [comment]
I have uploaded to Pypi an updated version that supports OSX 10.11 and above - pyre-check v.0.0.6.
Please let us know how that works.

**Comment by mingrammer** [comment]
@dark Thank you. I installed pyre successfully.
