### ISSUE TITLE
Pyre does not infer function return type?

### ISSUE THREAD

**Issue by dorafmon** [facebook/pyre-check#111]
Hi, I am experimenting with pyre and I have the following setup:

```
# pandas.pyi
def read_csv(file_path:str) -> DataFrame:...


class DataFrame:...
```

And `greeting.py`:

```
# pyre-strict

import pandas as pd

def greeting(name: str) -> str:
    return "Hello {}".format(name)


def get_dataframe_from_csv(file: str):
    return pd.read_csv(file)


greeting(get_dataframe_from_csv('/hello'))

```

When I invoke pyre from command line I got:
```
No watchman binary found.
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
 ƛ Found 2 type errors!
greeting.py:9:0 Missing return annotation [3]: Returning `pd.DataFrame` but no return type is specified.
greeting.py:13:9 Incompatible parameter type [6]: Expected `str` but got `unknown`.

```

My question here is it seems that pyre know that read_csv should return a DataFrame, but it does not assume `get_dataframe_from_csv` function return DataFrame if I do not explicitly specify it. Is this expected? Should pyre just assume that this function should return a DataFrame since it is just a warpper around pd.read_csv? To what extend pyre can infer a function's return type, or it does not try that at all an leave that to the user to annotate?

Sorry this is a novice quetion, I am very new to pyre. Thanks a lot.

**Comment by dark** [comment]
Hi, Pyre does not try to perform that inference you mention, and instead does not type-check functions that are not annotated. This is because the inferred type might not exactly match the intent of the API.

For example, in your case `pd.read_csv()` returns a `DataFrame`, but maybe the API of `get_dataframe_from_csv` is that it should return an instance of one of `DataFrame` superclasses. If we were to infer `DataFrame`, this could possibly create spurious errors in the users of `get_dataframe_from_csv`, where an instance of a superclass is instead expected.

For this reason, we rely on the explicit type annotation by the user, that should know better about the intended interface.

**Comment by dark** [comment]
No further action item here, hence closing.

Please reopen/file a new issue if you have a follow-up question, thanks.
