### ISSUE TITLE
No module named 'pyre_check.sapp.sapp.extensions'

### ISSUE THREAD

**Issue by 1one-w01f** [facebook/pyre-check#151]
Hi,

I built Pyre from source, and then built a pypi package, and installed it on my pyenv environment running Python 3.7.2.

Most of the examples from [https://pyre-check.org/docs](https://pyre-check.org/docs) worked fine, except the one involving SAPP. When I invoke `sapp`, I get the following error:

```
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.2/bin/sapp", line 6, in <module>
    from pyre_check.sapp.sapp.cli import cli
  File "~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyre_check/sapp/sapp/cli.py", line 5, in <module>
    from .cli_lib import commands, common_options
  File "~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyre_check/sapp/sapp/cli_lib.py", line 18, in <module>
    from .extensions import prompt_extension
ModuleNotFoundError: No module named 'pyre_check.sapp.sapp.extensions'
```

Any clues to whether I have missed something?

**Comment by jerryliu55** [comment]
Hey @1one-w01f, thanks for reporting this.

At a glance, it looks like the issue is on our end. We're missing an `__init__.py` file in the extensions directory, so python's setuptools doesn't recognize it as a module. I think a temporary fix for you is to run `touch <path_to_pyre>/sapp/sapp/extensions/__init__.py` and then rebuild the package.

Meanwhile I'll test this theory and get back to you shortly :)

**Comment by 1one-w01f** [comment]
@jerryliu55 Thank you for your prompt response. SAPP is running now after rebuilding the latest commit.
