### ISSUE TITLE
Optional arguments are not handled

### ISSUE THREAD

**Issue by lkgarrison** [facebook/pyre-check#178]
## Repro cases
I expected to be able to mark a parameter as optional two different ways. However, pyre threw an error for both:

### Case 1
This case seems like it directly 
```
def foo(bar: int, baz: Optional[int]) -> str:
    return 'foo'
my_foo: str = foo(1)
```
Error: "_Missing argument [20]: Call `test.foo` expects argument `baz`._"

### Case 2
I'm unsure if this type is officially supported by PEP 526, but both mypy and pytype handle this case correctly:
```
def foo(bar: int, baz: int = None) -> str:
    return 'foo'
my_foo: str = foo(1)
```
Error: Error: "_Incompatible variable type [9]: baz is declared to have type `int` but is used as type `None`_"

## Environment
Python version: 3.7.1
pyre version: 0.0.27
OS: Mac

**Comment by JelleZijlstra** [comment]
Regarding your first case, `Optional` means that the argument may be None, not that it can be omitted. Your code will throw an error at runtime and pyre is correct to reject it.

For case 2, you should also type the argument as `Optional[int]`. Mypy historically made arguments implicitly Optional when the default is None, but that behavior was changed because it was considered confusing. Pyre is again correct to reject your program.

**Comment by dkgi** [comment]
@lkgarrison, I hope that answers the question? Feel free to reopen if not.
