### ISSUE TITLE
Pyre can't find the flow

### ISSUE THREAD

**Issue by Rasoul-Jahanshahi** [facebook/pyre-check#215]
Consider the following python examples:
test1.py
```python
link = "https://google.com"
def get_content(url):
    html = requests.get(url)
    return html

def test():
    res = get_content(link)
    os.system("echo " + str(res.status_code))

test()
```

test2.py
```python
link = "https://google.com"
def get_content(url):
    html = requests.get(url)
    return html

res = get_content(link)
os.system("echo " + str(res.status_code))
```

taint stubs is:
```python
def requests.api.get(url=..., params=..., **kwargs=...) -> TaintSource[URL]: ...
def os.system(command: TaintSink[RemoteCodeExecution]): ....
```
and taint config is:
``` 
sources: [
{
    name: "URL",
    comment: "the outside world content"
}
],
sinks: [
{
      name: "RemoteCodeExecution",
      comment: "use to annotate execution of code"            
}
],
features: [],
rules: [
{
      name: "Possible Shell Injection",
      code: 5002,
      sources: ["URL"],
      sinks: ["RemoteCodeExecution"],
      message_format: "Data from [{$sources}] may reach [{$sinks}]"
}
]
}
```
Pyre finds the flow in test1.py but it can't find the same flow in test2.py. Am I missing something here?
or the configuration is wrong?

**Comment by sinancepel** [comment]
Two notes:

1. The taint analysis doesn't deal well with toplevels at the moment, could you move the sink to a function?

2. It looks like you've created a taint model for `requests.api.get` but are calling requests.get (without importing the module). Could you try directly tainting requests.get, importing the module and seeing if that helps?

**Comment by Rasoul-Jahanshahi** [comment]
If I move the sink to a function, it works fine( test1.py).
I used the sample config file in the git repo itself for the taint model of ```requesets.api.get```.

**Comment by gbleaney** [comment]
@Rasoul-Jahanshahi on the `requests.api.get` vs `requests.get` point that @sinancepel brought up in 2), the models we provide should be fine since [typeshed gives us the information we need to know that both `get` functions are the same](https://github.com/python/typeshed/blob/f7f68607ab910595d0076b2003d78a364f96c8a8/third_party/2and3/requests/__init__.pyi#L22).

@sinancepel 's point in 1) explains the difference you're seeing between `test1.py` and `test2.py`. A limitation of Pysa is that it does not tack taint flows through variables at the global scope. Flows will need to be within the scope of a function to be caught. We've talked about ways to make this work, but for the time being `test2.py` isn't going to work.

Does that all make sense?

**Comment by Rasoul-Jahanshahi** [comment]
Thanks a lot.
I was going to create a new issue and mention that there is a problem with tracking global variables ( even if you use them inside a function.)

**Comment by sinancepel** [comment]
In that case, closing this issue :) We have known limitations with tracking global variables that we can expand on in that issue.
