### ISSUE TITLE
List comprehensions with optional values

### ISSUE THREAD

**Issue by aspin** [facebook/pyre-check#250]
With new changes to how strictly optional values are handled, is there a correct way to do list comprehensions that filter on that optional attribute not None?

For example:

```python
@dataclass
class Data:
    field: Optional[str]

some_datas = [Data(None), Data("foo"), Data("bar")]

# error, because this is a List[Optional[str]]
fields: List[str] = [data.field for data in some_datas if data.field is not None] 
```

**Comment by aspin** [comment]
I suppose this works, but is that the only way to do things?

```python
fields: List[str] = [data_field for data_field in (data.field for data in some_datas) if data_field is not None]
```

**Comment by arthaud** [comment]
Hi @aspin,

This is indeed the typical optional refinement problem. We are not allowed to deduce that `data.field` is not `None` because it could be updated by another thread.

The usual workaround is to create a local variable. In your case, since you are using a comprehension list, you would need to create another temporary list/generator, as in your example. I found another way that is shorter, not sure if you prefer it:
```python
fields: List[str] = list(filter(None, data.field for data in some_datas))
```

Another workaround is to type `field` as `Final[Optional[str]]` if it is immutable.
