### ISSUE TITLE
Pyre can't find redirected imports

### ISSUE THREAD

**Issue by dirn** [facebook/pyre-check#287]
When trying to import something is actually a redirected import, `pyre` can't find the name. For example

    from django.urls import reverse

results in

    Undefined import [21]: Could not find a name `reverse` defined in module `django.urls`.

whereas

    from django.urls.base import reverse

passes.

I'm running into this in PyGotham/awards#78, but I'm able to reproduce this in a file that just contains the import.

**Comment by arthaud** [comment]
Hi @dirn, thanks for the report.

This is due to a bug in our stubs. Since PEP 484: `Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form.`. Most of our django stubs use `from .. import ..` which means that they don't export ".." even though they should. I will fix that soon and it should be included in the next release.

**Comment by arthaud** [comment]
Fixed in 676acecf5d9308241796cd8b2eacb71a94d46b66
