### ISSUE TITLE
pyre venv (virtualenv) support

### ISSUE THREAD

**Issue by cooperlees** [facebook/pyre-check#316]
Is using pyre from a Python virtualenv *(venv)* supported?

pyre recommends setting a configuration file. This file is very rigid and hard codes paths within a venv and I have to add them to ignore. I'd like to be able to use `pyre` from a venv of any path and not have to update the config file to do so.

If I leave these hard set values out of the config I get:
```console
 ƛ Invalid configuration:  `/private/tmp/tp/lib/stdlib` is not a valid directory.
```

## Repro
From the root of the `ptr` repo:
```console
python3 -m venv /tmp/tp
/tmp/tp/bin/pip install -U pip setuptools pyre-check
/tmp/tp/bin/pyre
 ƛ Invalid configuration:  `/private/tmp/tp/lib/stdlib` is not a valid directory.
```

**Goal**: I'd like to just run `pyre` from an activated (ideally a non activated too) venv via [ptr](https://github.com/facebookincubator/ptr)

If this is never going to be supported just say so, and I'll remove it from ptr. If it is, and we get it work again, I'll offer helping adding some CI to ensure this does not regress again.

**Comment by grievejia** [comment]
I think running `pyre` from one activated venv is already supported, provided that the venv directory is not located under the source directory being checked, no? 

Running `pyre` from multiple venvs without changing the configuration file is indeed not possible at the moment. Would something like #317 where configurations options can be overridden on the cli address this for you? I can start looking into that next week.

**Comment by cooperlees** [comment]
This is what I expect to be the major blocker yes.

I also think it needs to resolve symlinks based on ` ƛ Invalid configuration:  `/private/tmp/tp/lib/stdlib` is not a valid directory.`

**Comment by luizribeiro** [comment]
I think it would be great to have #317 for this. I've been running into issues after 0.0.52 like others on this thread on my projects that rely on pyre.

Also, because on my local machine I tend to have my venvs setup with `poetry` under the local directory (`.venv`), I often need to mess around with my `.pyre_configuration` on Travis - since Travis has a virtual environment of its own. Ideally `pyre` would detect that there is a virtual environment and use its search paths (and ignore errors on those search paths) automatically - thus not requiring you to even have a `.pyre_configuration` file in the first place.

**Comment by gbleaney** [comment]
@cooperlees we just fixed a bug with the resolution of the typeshed folder in v0.0.56. Would you mind retesting with that release? FWIW, I've had pyre running out of a virtual environment for the pysa tutorial and it's worked fine (before briefly becoming broken with the most recent release.

**Comment by cooperlees** [comment]
Apart from MacOS timing out (seems common on GitHub actions across my projects, it all looks fixed to me. I still had to add a config tho, but just only put in the source directories. I would love to not have to do that.

**Comment by cooperlees** [comment]
Sorry about that, will leave it to you for deciding if this is closable.

**Comment by xmo-odoo** [comment]
@grievejia 
> I think running `pyre` from one activated venv is already supported, provided that the venv directory is not located under the source directory being checked, no?

> Running pyre from multiple venvs without changing the configuration file is indeed not possible at the moment. 

This is a bit unclear, does that mean pyre automatically picks up the active venv's site-package and adds it to its search-path, or that the search path has to be updated to explicitly add the venv's path?

**Comment by grievejia** [comment]
> does that mean pyre automatically picks up the active venv's site-package and adds it to its search-path, or that the search path has to be updated to explicitly add the venv's path?

Right now you'll have to explicitly add packages to the configuration but you don't need the full path of the site package -- just the name of the package is sufficient since pyre can use `site.getsitepackages()` to determine the path:
```
{
  ...
  "search_path": [
    ...,
    { "site-package": "click" },
    { "site-package": "attrs" }
  ],
}
```
I don't think we support adding all site packages to search path automatically at the moment. It shouldn't be too hard to add now though. One consideration is that adding tons of code to the search path will slow down the checking since pyre will at least try to parse every source file that gets added. So if the venv has lots of packages installed I think it would still be nice to have a way to opt out the auto-search-path-adding. Perhaps this functionality can be exposed via a flag?
