### ISSUE TITLE
Missing XSS SINK_NAME for django.http.response.HttpResponse.__init__

### ISSUE THREAD

**Issue by bedirhan** [facebook/pyre-check#331]
https://github.com/facebook/pyre-check/blob/037d7c022bbc54041322843c08d4dad9311bf6fa/stubs/taint/core_privacy_security/django_sources_sinks.pysa#L53

I'm new to pysa (excellent tool), but I couldn't nail a basic XSS below as is;

```
# On a totally different note, without the below line, XSS is missed again (app works, tough). That's a pity but a requirement I guess. 
from django.http import HttpRequest
from django.http import HttpResponse

def index(request : HttpRequest):
    return HttpResponse("Hello, world." + request.GET.get('message'))
```

So, I appended the XSS SINK_NAME and it works.

**Comment by gbleaney** [comment]
Hey @bedirhan, I'm glad you're liking the tool and thanks for the feedback! We ended up making the choice to leave that sink out, because it created a ton of noise (turns out we put a lot of user controlled content into the pages we render) and didn't really help catch bugs in the way we render pages internally. That being said, I think that this sink adds value for the open source community. Would you be willing to send us a PR? I'd be happy to merge it :).

**Comment by bedirhan** [comment]
I see... You could probably have a sanitizer, but still, there must also be a performance cost. I should really leave it to you guys. thanks for the fast response.

**Comment by gbleaney** [comment]
A sanitizer doesn't quite work, because we do still want to detect data flowing into the `content` argument as a `ReturnedToUser` sink. Our approach would likely be to filter after the fact when browsing XSS issues, and just removed ones that reach `content`.

**Comment by bedirhan** [comment]
hmmm, I just realized that sanitizers are universal in pysa...

**Comment by gbleaney** [comment]
Yup, unfortunately. We do have some enhancements that are coming soon though that will (mostly) fix that.
