### ISSUE TITLE
Is there any chance of type-checking Python 2 code?

### ISSUE THREAD

**Issue by radix** [facebook/pyre-check#35]
PEP 484 defines an optional syntax for supporting type annotations for Python 2 code, and PEP 526 also refers to support for Python 2 by way of stub files.

Is there any chance that Pyre will support type-checking Python 2-compatible code?

If not, it would be good to more explicitly document the supported versions of Python on the web site or in the documentation.

**Comment by dkgi** [comment]
We support parsing of the annotations but supporting 2.7 is an explicit non-goal. We should definitely put that in the documentation. Thanks for pointing it out.

**Comment by dkgi** [comment]
Made the "Python 3" explicit on our front-page: https://pyre-check.org/

**Comment by drvink** [comment]
Could you elaborate on why it is an "explicit non-goal"? Would a PR be accepted that added support? I'm afraid that in 2018 there continues to be "the Python people actually use" and "the Python they want you to use", especially given the many programs that embed or otherwise use Python 2.7 as an extension language.

**Comment by gvanrossum** [comment]
You could use [mypy](https://pypi.org/project/mypy/) instead. It works great for Python 2 *and* 3. :-)

**Comment by dark** [comment]
@drvink Supporting Python 2 is not just adding new code via a PR. It is also requires maintenance, testing, support and infrastructure.
Since we are a small team, we need to focus on the goals that are most important for us.
Python 2 will reach EOL sometime in 2020; hence, the long-term goals for Pyre are focused on working with Python 3 codebases, for the purpose of supporting deeper static analysis tools, as more deeply presented at our talk at PyCon:  https://www.youtube.com/watch?v=hWV8t494N88 .

**Comment by drvink** [comment]
Thanks; that's a much better answer.
