### ISSUE TITLE
Ignoring/skipping invalid models without terminating the analysis

### ISSUE THREAD

**Issue by vincent-musedev** [facebook/pyre-check#369]
While running pyre against many repositories using the core *.pysa files the vast majority (all) of our analyses are failing with errors such as:

```
2021-01-15 00:08:40,654 [PID 371] ERROR Invalid model for `django.http.request.HttpRequest.REQUEST` defined in `/code/.musepysa/django_sources_sinks.pysa:11`: Class `django.http.request.HttpRequest` has no attribute `REQUEST`.
```

Is it possible to add a flag to downgrade model issues to warnings and ignore the affected models, or is this indicative of a misconfiguration somewhere?

**Comment by gbleaney** [comment]
This isn't a configuration problem; sadly it's actually a sign you're probably set up right. The reason you're getting a bunch of invalid models is that we ship a TON of models with Pysa these days, and not everyone uses the libs these models correspond to. If you have a model for a lib which is not in your venv, Pysa will think the model is invalid because it can't find the source code of the library to compare against.

This is a problem we need to make better for the open source experience, which is something we're actively investing in this half (I actually just added a note about this exact problem to our plans this week).

The short term fix is using the `--no-verify` flag, so that analysis will proceed despite the failing models.

**Comment by gbleaney** [comment]
Closing out the issue because I think it's been resolved, but feel free to re-open if you have more questions!
