### ISSUE TITLE
Add flask_mysql cursor execute as sink

### ISSUE THREAD

**Issue by pzsette** [facebook/pyre-check#390]
I'm testing Pysa to detect vulnerabilities in my flask web application, but i can't add `flask_mysqldb` commands as Pysa sinks.
If i run `pyre analyze --no-verify` Pysa doesn't detect this as a vulnerability

```
from flask_mysqldb import MySQL

db = MySQL(app)

email = request.form['email']
cursor = db.connection.cursor()

query = "SELECT * FROM accounts WHERE email ='"+email+"'"
cursor.execute(query)
```
Should i add a new sink in `.pysa` files in taint folder ?

**Comment by gbleaney** [comment]
It looks like `flask_mysqldb` just creates a `MySQLdb` connection and returns it:
https://github.com/alexferl/flask-mysqldb/blob/9d5cd92517f1d1a052660c6aa324b2df067190ef/flask_mysqldb/__init__.py#L81

We actually have taint models for `MySQLdb` already:
https://github.com/facebook/pyre-check/blob/master/stubs/third_party_taint/mysqldb_sinks.pysa

The real problem here is that `flask_mysqldb` doesn't have type information, so in your code Pyre doesn't know that `db.connection` is a `MySQLdb` connection object. There are two possible solutions here:

1. (better, but slower) Send a PR to `flask_mysqldb` and get them to update the functions in [this file](https://github.com/alexferl/flask-mysqldb/blob/master/flask_mysqldb/__init__.py) with type annotations, so that Pyre can correctly determine the return type of those functions. Once a new PyPI package is shipped with that type information, Pyre should be able to pick it up from your venv (assuming your `.pyre_configuration` includes your venv in the search path)
2. (ok, but faster) Create your own [type stubs](https://www.python.org/dev/peps/pep-0484/#stub-files) in your local project, to tell Pyre TODO. You'll need to include these stubs in your [`search_path` in your `.pyre_configuration`](https://pyre-check.org/docs/configuration#the-global-configuration)

**Comment by pzsette** [comment]
I've added `search_path` in my `.pyre_configuration.local` and create a `flask_mysqldb.pyi` file with stubbed method inside flask_mysqldb folder,  but Pyre can't still determine the return type of the functions.
```  
"search_path": [
    "./flask_mysqldb"
  ]
```
flask_mysqldb.pyi
```
import MySQLdb

class MySQL(object):
    @property
    def connection(self) -> MySQLdb.Connection: ...
```

**Comment by gbleaney** [comment]
> I've added `search_path` in my `.pyre_configuration.local`

I believe fields in `.pyre_configuration.local` will override fields in the  `.pyre_configuration` file, so be careful you're not inadvertently overriding the search path in the `.pyre_configuration` at the root of your repo.

> but Pyre can't still determine the return type of the functions.

Two things here:

1. It looks like [`MySQLdb` is also missing type information, so you probably also need a stub there](https://github.com/PyMySQL/mysqlclient/blob/24aaa72c1503fe35cb1d0584ad553b41d10ddb48/MySQLdb/connections.py#L246)
2. Can you insert some [`reveal_type` calls](https://pyre-check.org/docs/pysa-tips#reveal_typeyour_variable) into your code and then run `pyre analyze` again on it? The commands should look something like this:
```
db = MySQL(app)

email = request.form['email']
reveal_type(db)
reveal_type(db.connection)
reveal_type(db.connection.cursor)
cursor = db.connection.cursor()
reveal_type(cursor)
reveal_type(cursor.execute)

query = "SELECT * FROM accounts WHERE email ='"+email+"'"
cursor.execute(query)
```
You should see messages in the output of the `pyre analyze` command telling you the revealed type at each of those calls. Those messages will give us more to work with debugging here.

You can also try messing around with the [`reveal_taint`](https://pyre-check.org/docs/pysa-tips#reveal_taintyour_variable) command to confirm that Pysa is correctly detecting `email` as a source of `UserControlled` data

**Comment by pzsette** [comment]
these are the messages from reveal_type:
```
../run.py:6:0 Revealed type [-1]: Revealed type for `database.db` is `typing.Any`.
../run.py:7:0 Revealed type [-1]: Revealed type for `database.db.connection` is `unknown`.
../run.py:8:0 Revealed type [-1]: Revealed type for `database.db.connection.cursor` is `unknown`.
auth.py:24:12 Revealed type [-1]: Revealed type for `cursor` is `typing.Any`.
auth.py:25:12 Revealed type [-1]: Revealed type for `cursor.execute` is `unknown`.
```

**Comment by gbleaney** [comment]
What is `database`? That doesn't seem to match your example code. Since we see `database.db` is `Any`, we're not getting the tying right on that attribute, so nothing after that point is going to work. Can you include the definition of the class of which `database` is an instance, especially the bit where the `db` the property or attribute is defined? We'll need to get the typing right on `database.db` before anything else can work.

**Comment by pzsette** [comment]
sorry, in the first example i was merging all together for simplicity, the database.py file is very simple:
```
from flask_mysqldb import MySQL

db = MySQL()
```
then in the run.py
```
from app import create_app

app = create_app()
db.init_app(app)
```
this is the class where create_app is defined:
```
from flask import Flask
app = Flask(__name__)
app.config.from_object('config')


def create_app():
    from app import auth, home, idcard

    with app.app_context():
        app.register_blueprint(auth.bp)
        app.register_blueprint(home.bp)
        app.register_blueprint(idcard.bp)

    return app
```

**Comment by gbleaney** [comment]
@pzsette Can you also include where `db.connection.cursor()` and `cursor.execute(query)` are called in your example? And can you ask try editing `database.py` to be `db: MySQL = MySQL()`, then re-run pysa and give me the updated `reveal_taint` output?

**Comment by pzsette** [comment]
i edited the previous comment with cursor class and this is the updated `revelation_taint`:
../run.py:6:0 Revealed type [-1]: Revealed type for `database.db` is `flask_mysqldb.MySQL`.
../run.py:7:0 Revealed type [-1]: Revealed type for `database.db.connection` is `unknown`.
../run.py:8:0 Revealed type [-1]: Revealed type for `database.db.connection.cursor` is `unknown`.
auth.py:25:12 Revealed type [-1]: Revealed type for `cursor` is `typing.Any`.
auth.py:26:12 Revealed type [-1]: Revealed type for `cursor.execute` is `unknown`.

**Comment by gbleaney** [comment]
Alright, it looks like we've solved the problem for `database.db` being `Any`! Next step: why is `database.db.connection` `unknown`? Let's look at a few things:

1. What's your directory structure? Above you said you had `search_path` as `./flask_mysqldb` in `.pyre_configuration.local`? Does that mean you have a `./flask_mysqldb/fask_mysqldb.pyi`? That's what you'd need to properly pick up the `fask_mysqldb.pyi` file.
2. You got a `Could not find a module corresponding to import 'MySQLdb'.` errror. This indicates to me that Pyre doesn't see the code for `MySQLdb`. Assuming that's in your venv, can you add your venv to your `search_path`? It should look something like `/path/to/venv/lib/python3.7/site-packages/`
3. You got a `Annotation 'object' is not defined as a type.` This implies that Pyre doesn't know where it's copy of typeshed is. This _should_ have been configured when you ran `pyre init`, but it can also be manually configured by pointing the [`typeshed` entry in `.pyre_config`](https://pyre-check.org/docs/configuration#the-global-configuration) to the typeshed dir in your venv. Something like `/path/to/venv/lib/pyre_check/typeshed/`.

After those changes, let's see what the revealed types look like

**Comment by pzsette** [comment]
this is the updated `.pyre_configuration` file, Pyre is not in venv
```
{
  "source_directories": [
    "."
  ],
  "taint_models_path": "/Library/Frameworks/Python.framework/Versions/3.8/lib",
  "typeshed" : "/Library/Frameworks/Python.framework/Versions/3.8/lib/pyre_check/typeshed/",
  "ignore_all_errors": ["venv"],
  "search_path": [
    "./flask_mysqldb",
    "./venv/lib/python3.8/site-packages/"
  ]
}
```
unfortunately if run `pyre` i got same as before:

```
app/auth.py:24:12 Revealed type [-1]: Revealed type for `cursor` is `typing.Any`.
app/auth.py:25:12 Revealed type [-1]: Revealed type for `cursor.execute` is `unknown`.
flask_mysqldb/cursor.pyi:3:17 Undefined or invalid type [11]: Annotation `_mysql.connection` is not defined as a type.
flask_mysqldb/flask_mysqldb.pyi:5:28 Undefined or invalid type [11]: Annotation `MySQLdb.Connection` is not defined as a type.
run.py:5:0 Undefined attribute [16]: `flask_mysqldb.MySQL` has no attribute `init_app`.
run.py:6:0 Revealed type [-1]: Revealed type for `database.db` is `flask_mysqldb.MySQL`.
run.py:7:0 Revealed type [-1]: Revealed type for `database.db.connection` is `unknown`.
run.py:8:0 Revealed type [-1]: Revealed type for `database.db.connection.cursor` is `unknown`.
```

here there's a screenshot of my project files if can help 
https://imgur.com/L65E6cd

**Comment by gbleaney** [comment]
> this is the updated `.pyre_configuration` file

Just to be clear, we're no longer working with a `.pyre_configuration.local` file? It's just that one in the root of `WebAppStaticAnalysis`?

> unfortunately if run `pyre` i got same as before

This is actually progress! The lack of `Annotation 'object' is not defined as a type.` means that Pyre is finding typeshed correctly. Let's break down the other errors:

```
flask_mysqldb/cursor.pyi:3:17 Undefined or invalid type [11]: Annotation `_mysql.connection` is not defined as a type.
```

I don't 100% know what's going on here, since you haven't provided the source of `cursor.pyi`, but I'm not sure why this file exists. Given that you've got `flask_mysqldb/` configured as your search path, this file is where Pyre will look when you do `from cursor import XXX`. Do you have any such imports? If this was intended to add type information for `MySQLdb`'s `cursor`, it should be in `flask_mysqldb/MySQLdb/cursors.pyi` (as an aside, you should probably rename that `flask_mysqldb` folder, since it's a bit misleading of a name)

```
flask_mysqldb/flask_mysqldb.pyi:5:28 Undefined or invalid type [11]: Annotation `MySQLdb.Connection` is not defined as a type.
```

I think the proper annotation would be `MySQLdb.connections.Connection`, since that's [where the `Connection` class is defined](https://github.com/PyMySQL/mysqlclient/blob/24aaa72c1503fe35cb1d0584ad553b41d10ddb48/MySQLdb/connections.py#L51)

Also, I mentioned this above, but I'm putting it here again in case it got lost. [`MySQLdb` is also missing type information](https://github.com/PyMySQL/mysqlclient/blob/24aaa72c1503fe35cb1d0584ad553b41d10ddb48/MySQLdb/connections.py#L246), so you will need a stub file that covers at least the `cursor` function. You can try something like `pyre infer` or `stubgen` to automatically generate stubs and save you the effort of hand rolling them (might need to manually add the typing you care about after though).

```
run.py:5:0 Undefined attribute [16]: `flask_mysqldb.MySQL` has no attribute `init_app`.
```
This is because your `flask_mysqldb.pyi` stub file doesn't contain an `init_app` function (assuming it hasn't changed from what you [posted earlier](https://github.com/facebook/pyre-check/issues/390#issuecomment-792949684)). Stubs are all or nothing, if you have a `flask_mysqldb.pyi` file, Pyre will always look at that instead of the actual `flask_mysqldb.py` implementation file, so any function you want to use will need to appear in that file.

Once you've fixed all of the above errors, let's take another look at those `reveal_type`s

**Comment by pzsette** [comment]
Thank you so much for the help.
1.  I decided to make all pyre configurations inside `.pyre_configuration` file and delete `.pyre_configuration.local`. I hope that is safe to do this.

```
{
  "source_directories": [
    "."
  ],
  "taint_models_path": "/Library/Frameworks/Python.framework/Versions/3.8/lib",
  "typeshed" : "/Library/Frameworks/Python.framework/Versions/3.8/lib/pyre_check/typeshed/",
  "ignore_all_errors": ["venv"],
  "search_path": [
    "./flask_mysqldb",
    "./venv/lib/python3.8/site-packages/"
  ]
}
```
2. I made some changes inside flask_myqldb folder, now i have three `.pyi` files:
*  `flask_mysqldb.pyi`
```
import MySQLdb

class MySQL(object):
    @property
    def connection(self) -> MySQLdb.connections.Connection:...

    def init_app(self,app):...
```
* ` connections.pyi`
```
import MySQLdb

class Connections(MySQLdb.connections.Connection):
    def cursor(self, cursorclass=None) -> MySQLdb.connections.Connection:...
```

* ` cursors.pyi`
```
class BaseCursor:
    @property
    def execute(self, query):...
```

if i run `pyre`: 
```
app/auth.py:24:12 Revealed type [-1]: Revealed type for `cursor` is `typing.Any`.
app/auth.py:25:12 Revealed type [-1]: Revealed type for `cursor.execute` is `unknown`.
run.py:6:0 Revealed type [-1]: Revealed type for `database.db` is `flask_mysqldb.MySQL`.
run.py:7:0 Revealed type [-1]: Revealed type for `database.db.connection` is `MySQLdb.connections.Connection`.
run.py:8:0 Revealed type [-1]: Revealed type for `database.db.connection.cursor` is `BoundMethod[typing.Callable(MySQLdb.connections.Connection.cursor)[[Named(self, MySQLdb.connections.Connection), Named(cursorclass, unknown, default)], typing.Any], MySQLdb.connections.Connection]`.
```

**Comment by pzsette** [comment]
Yes both `connection.pyi` and `cursors.pyi` are inside MySQLdb folder.
I think i'm close to solve the problem but i can't correctly stub [this](https://github.com/PyMySQL/mysqlclient/blob/24aaa72c1503fe35cb1d0584ad553b41d10ddb48/MySQLdb/connections.py#L246) method. This is my `connection.pyi` file:
```
import MySQLdb

class Connections(MySQLdb.connections.Connection):
    def cursor(self, cursorclass=None) -> MySQLdb.cursors.BaseCursor:...
```
PyCharm however suggests that this "overrides method in Connection".

I added other `reveal_type` to my code in `auth.py` file:

```
cursor = db.connection.cursor()
reveal_type(db)
reveal_type(db.connection)
reveal_type(db.connection.cursor())
reveal_type(cursor)
reveal_type(cursor.execute)

query = "SELECT * FROM accounts WHERE email ='"+email+"'"
```
and i got this report from `pyre`
```
app/auth.py:24:12 Revealed type [-1]: Revealed type for `database.db` is `flask_mysqldb.MySQL`.
app/auth.py:25:12 Revealed type [-1]: Revealed type for `database.db.connection` is `MySQLdb.connections.Connection`.
app/auth.py:26:12 Revealed type [-1]: Revealed type for `database.db.connection.cursor()` is `typing.Any`.
app/auth.py:27:12 Revealed type [-1]: Revealed type for `cursor` is `typing.Any`.
app/auth.py:28:12 Revealed type [-1]: Revealed type for `cursor.execute` is `unknown`.
```
So it seems that pyre can't still determine `cursor` type (I think it should be `MySQLdb.cursors.BaseCursor`).

**Comment by gbleaney** [comment]
> I think i'm close to solve the problem but i can't correctly stub this method. This is my `connection.pyi` file:

One problem I see is that your class is called `Connections` not `Connection`. I also don't think the inheritance from `MySQLdb.connections.Connection` is needed. Can you try something like this for `connection.pyi`?

```
import MySQLdb

class Connection:
    def cursor(self, cursorclass=None) -> MySQLdb.cursors.BaseCursor:...
```

> So it seems that pyre can't still determine cursor type (I think it should be `MySQLdb.cursors.BaseCursor`).

Yeah, that's what I think should be happening too. I'm hoping the above change to the stub file should fix it.

**Comment by gbleaney** [comment]
In your message you use both `connection.pyi` and `connections.pyi`. Just to clarify, you are using `connections.pyi` (with the `s`), right? That's the name of the file in `MySQLdb`.

> i tried to edit `cursor()` in `connections.pyi` with `stubgen` result but it doesn't work.

Are you getting an error, or is it just not having any effect? And to confirm, the edit looked like this, right?

```
import MySQLdb
....
    def cursor(self, cursorclass: Optional[Any] = ...) -> MySQLdb.cursors.BaseCursor: ...
```

**Comment by pzsette** [comment]
* yes sorry, the filename is `connections.pyi`.
* just no effect, same report i have pasted before.
*  yes, now the `connections.pyi` is:
```
import MySQLdb
from typing import Any, Optional

class Connection:
    def cursor(self, cursorclass: Optional[Any] = ...) -> MySQLdb.cursors.BaseCursor: ...
```

**Comment by gbleaney** [comment]
Hmm, alright, I'm at a bit of a loss for what other bugs there might be. Can you put your repro up in a GH repo or something that I can clone and test on locally?

**Comment by pzsette** [comment]
sure, this's the repo i'm using https://github.com/pzsette/WebAppStaticAnalysis/tree/with-vulnerability
I want to apologize in advance for my bad code. I'm a student and python beginner.
