### ISSUE TITLE
Can pyre check both the .py and .pyi at the same time and make sure the .py implements .pyi?

### ISSUE THREAD

**Issue by aryx** [facebook/pyre-check#568]
I want to define the interface of foo.py in a separate file foo.pyi, but then when I tried mypy, I get errors because mypy can check only one of them.
See https://github.com/returntocorp/semgrep/pull/4534 for example.
Can pyre check both the .py and .pyi?

**Comment by aryx** [comment]
For example with pyre, if I create a foo.py containing a function foo(), and later define a foo.pyi declaring this function foo,
then whatever I do in foo.py is not checked anymore. It's like pyre consider that the .pyi has precedent over the .py and does not check anymore the code in it.

**Comment by kbansal** [comment]
Hi, Thanks for your interest in Pyre. As far as I know, that is not possible.

(CC @grievejia, in case have any additional context on this)

**Comment by shannonzhu** [comment]
@aryx  Hi! Curious to clarify what the expected behavior would be here. Currently, we do consider the .pyi as taking precedence over the .py file, because there's nothing guaranteeing that the two files are actually consistent. Many users will use a .pyi file to override the types of some very dynamic or hard-to-annotate APIs and provide a simple or gradual interface. 

Even if that were not an intended use case, what should happen if a function has a different signature in the .py vs. the .pyi? It seems potentially confusing to type check every other module with the .pyi signature, and type check the current module with the .py signature. Let me know if that lines up with your feature request, or if you had a different behavior in mind? 

Thanks for your input!

**Comment by arthaud** [comment]
I am just guessing but I think the point is that pyre will only check the `.pyi` and not the `.py`, but there could be type errors in the `.py` (e.g, in function bodies). I think this is a valid point.
Checking the consistency between the `.pyi` and the `.py` is another problem.

**Comment by aryx** [comment]
Just to clarify, I'm mainly an OCaml programmer and I love having a .mli defining the interface implemented in a .ml. This forces developers to think in terms of interfaces (interface in the original sense of the meaning, not in the Java/Python/.. class oriented meaning), this makes it more obvious when the interface of a module is just too big and messy, and it just provides clear boundaries of what the external user of a module can do with a module. To me this is 101 software engineering, so I would love to have the same experience in Python. I know Python is not OCaml, and the spirit of people there is different, but in the last decades we've seen people understanding the value of types, and signatures, so I think there is a very small delta to implement to get the full values of .pyi to also enforce interface.

The feature I'm requesting is that if in the same directory there is a foo.pyi and a foo.py, then pyre (if needed with a certain flag, like -really-strict), would check both files and make sure they are consistent with each other. Moreover, when checking other files in this directory, we should use only the information in foo.pyi to typecheck bar.py, so bar.py could only use the entities defined in foo.pyi (enforcing strong boundaries between modules).

My main use case is that people in our team are creating huge files with lots of helpers functions that are meant to be private (sometimes they put a leading _ in the name), and other modules are using those helpers functions when they should not. Moreover, it's very hard to understand the codebase because you have this huge foo.py to read where it would be so much better to have a cleaner/restricted/documented interface in foo.pyi that just exposes what the user of the module should know and use.

**Comment by grievejia** [comment]
The relation between `.pyi` and `.py` file is defined to be very different from the relation between `.mli` and `.ml` file. In the OCaml case, `.mli` files are supposed to be the "interfaces" whereas `.ml` files are supposed to be the implementations that corresponds to the `.ml` files. But in Python, `.pyi` file has nothing to do with this interfaces/implementation distinction. The sole reason why it exists is to allow people add "overriding" type signatures to untyped codebases whose authors are unwilling to add any typing. It's more of a "backward-compatibility" feature and if you are not writing untyped Python yourself, inline annotations should always be preferred. 

If you look at PEP 484, it specifically does not define any requirements that the contents of `.pyi` file and the corresponding `.py` file must "match" each other. As Shannon mentioned, there are even legitimate cases where such a "match" is either undesirable or impossible to validate. 

>  it would be so much better to have a cleaner/restricted/documented interface in foo.pyi that just exposes what the user of the module should know and use.

See my comment above -- this used case is not what `.pyi` files are designed for so I would recommend against it. 

That said, I think name hiding is a legitimate feature request and I don't think currently there exists any standardized way to do that in Python (except the leading `_` convention). It might be a good candidate topic to bring up with the [`typing-sig`](https://mail.python.org/archives/list/typing-sig@python.org/) community so people could get a consensus on what's the best way to do it. My guess would be that using a decorator to mark hidden function would be a more preferable approach over abusing the `.pyi` files.

**Comment by shannonzhu** [comment]
I agree it would be harmful to try to re-use the concept of a `.pyi` file as a interface definition because of its use case as an escape hatch. As @grievejia said, the explicit expectation is that stub files are either not entirely consistent with the underlying `.py` module, or not owned by the same authors. We really try to encourage the deletion of `.pyi` files the moment they become consistent with the underlying `.py` file. Throwing errors even in an opt-in "stricter" mode if they are inconsistent would add a lot of confusion.

I could see an argument as @arthaud  mentioned above for wanting to still trigger type checking on the bodies of modules that are overshadowed by a `.pyi` file (when the stub file is not consistent and therefore must remain) because we don't want to lose all typing guarantees on those function bodies. However, this seems like an edge case and we're not too pressed about losing type guarantees in a module where potentially sketchy band-aid patches are already required.
