### ISSUE TITLE
Invalid configuration: Configuration option `source_directories` cannot be overridden.

### ISSUE THREAD

**Issue by Jarvx** [facebook/pyre-check#602]
Hi,

I followed the setup documentation and managed to install the library. Then I ran the following command at the root of my Python project but obtained the error. 

`pyre init`

`pyre`

`ƛ Invalid configuration: Configuration option `source_directories` cannot be overridden.`

Can someone help with resolving this error? Please let me know if you need any additional information.

**Comment by Vishnu-Naik** [comment]
### Technical Reason
This issue is mainly occurring due to the fact that pyre wont accept configuration setting `source_directories` to be overwritten.

### Root cause for this issue
So, apparently for some reason pyre init creates a file called `.pyre_configuration.local` which is actually an extension file for `.pyre_configuration`. More info [here](https://stackoverflow.com/a/66110635)
There is no problem with creating `.pyre_configuration.local` but the problem is repeating configuration setting `source_directories`.

### Solution

A simple straight forward solution would be to rename `.pyre_configuration.local` to `.pyre_configuration`. I am assuming you are using pyre for the first time in your project, as you are running `pyre init`.
Now run `pyre` and pyre should type check now without throwing any error. 

If you already have a `.pyre_configuration` file in your project then remove `source_directories` from your `.pyre_configuration.local` file.

**Comment by Jarvx** [comment]
Many thanks! It works for me now.
