### ISSUE TITLE
How to check an extensionless python file?

### ISSUE THREAD

**Issue by akdor1154** [facebook/pyre-check#69]
My project has an executable script that has no extension, it just has `#!/usr/bin/env python3` at the top.
Currently pyre provides no way to check it. It would be great if it could do one of:
 - autodetect python scripts with a shebang and check them
 - allow hand-specifying a filename to check on the cli instead of / as well as a source directory
 - some other solution I have yet to think of.

**Comment by sinancepel** [comment]
The easiest thing to do would be to create a symbolic link to your script with a `.py` extension. Right now, the `.py` and `.pyi` extensions are necessary for pyre to analyze a file, so it's not possible to check the script directly. Assuming you're in a UNIX environment, running `ln my_script my_script.py` and `pyre check` should do the trick.

**Comment by akdor1154** [comment]
Thanks for the workaround. :) However my question was a bit tongue in cheek - i should probably have phrased it as a direct feature request.

**Comment by dark** [comment]
@akdor1154 The reason for which Pyre analyzes only `.py` files is because it operates on directories, and we try and follow the module discovery algorithm that the Python runtime uses: https://docs.python.org/3.6/tutorial/modules.html
Trying to autodetect files with a `python` shebang in a given directory could be counterintuitive for the user, as that is not the behavior of the runtime.

That said, I agree that it is sometime useful to type-check Python files that are not modules - e.g. configuration files written in Python, that might not have a `.py` extension. I think the best way would be specifying these files on the `pyre` commandline - that's a reasonable feature request.

**Comment by SamChou19815** [comment]
Looks like is has been implemented now. You can configure "extensions" in .pyre_configuration. See https://pyre-check.org/docs/configuration.html
