### ISSUE TITLE
Short form Enum('Color', ['Red', 'Blue']) does not work

### ISSUE THREAD

**Issue by ezyang** [facebook/pyre-check#698]
# Pyre Bug

**Bug description**
Pyre doesn't understand the two argument form of enum.Enum

**Reproduction steps**
```
import enum

Color = enum.Enum('Color', ['Red', 'Blue'])
print(Color.Red)
```

**Expected behavior**
It typechecks

**Logs**
```
$ pyre
ƛ Found 2 type errors!
a.py:3:8 Too many arguments [19]: Call `enum.Enum.__new__` expects 1 positional argument, 2 were provided.
a.py:4:6 Undefined attribute [16]: `enum.Enum` has no attribute `Red`.
```

Rage: https://gist.github.com/a5ac7a79e8896f73521a02e91838bec2

**Comment by pradeep90** [comment]
Hello @ezyang, this is fixed in master. The snippet works as expected in the [Pyre playground](https://pyre-check.org/play?input=%23%20Pyre%20is%20being%20run%20in%20gradual%20typing%20mode%3A%20https%3A%2F%2Fpyre-check.org%2Fdocs%2Ftypes-in-python%2F%23gradual-typing%0A%23%20Use%20the%20%60%23%20pyre-strict%60%20header%20to%20run%20in%20strict%20mode%2C%20which%20requires%20annotations.%0A%0Afrom%20typing%20import%20*%0Aimport%20enum%0A%0AColor%20%3D%20enum.Enum(%27Color%27%2C%20%5B%27Red%27%2C%20%27Blue%27%5D)%0Aprint(Color.Red)%0A).
