### ISSUE TITLE
Find lambdas are not checked correctly

### ISSUE THREAD

**Issue by eirnym** [facebook/pyre-check#810]
# Pyre Bug

**Bug description**
Please enter a clear and concise description of what the bug is.

I use `filter` function to filter out `None` values in a second value of sequence of pairs (`tuple` is used for the pair class). 

With `pyre-check 0.9.19` and Python 3.12.0 I have following error which is not correct as I filter out None values (`value[1] is not None` as shown below)

```
test.py:5:4 Incompatible return type [7]: Expected `Iterable[Tuple[str, str]]` but got `filter[Tuple[str, Optional[str]]]`.
```

**Reproduction steps**
Enter steps to reproduce the behavior.
I created an empty virtualenv, created a file `test.py` in empty folder with contents as shown below and run `pyre`

```python
from collections import abc
def filter_none(
    values: abc.Sequence[tuple[str, str | None]]
) -> abc.Iterable[tuple[str, str]]:
    return filter(lambda value: value[1] is not None, values)
```

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please include any relevant logs here:

```
Output goes here
```

Please run your reproduction steps followed by `pyre rage > pyre_rage.log`, and upload the file here:

[pyre_rage.log](https://github.com/facebook/pyre-check/files/13605372/pyre_rage.log)

**Additional context**
Add any other context about the problem here. (like dependencies in your venv, third party stub files being used, overall goals, etc.)

**Comment by ebrahimsofi123** [comment]
Hi! It looks like you're facing a type-checking issue with Pyre when filtering tuples that might contain `None` in their second element. Pyre seems to struggle with inferring that after filtering, the second element of the tuples is indeed always a string and not `None`. Normally, you'd expect Pyre to recognize that the lambda function ensures no `None` values remain in the second element, so the output should be `Iterable[Tuple[str, str]]`. However, it incorrectly interprets it as `Iterable[Tuple[str, Optional[str]]]`. A practical workaround is to use a list comprehension instead of the filter function. This alternative approach usually provides clearer type hints that help static analysis tools like Pyre understand the intended types more accurately.

**Comment by yangdanny97** [comment]
But to answer your question, we don't do any special analysis of the lambda of the filter function to refine types. The other major typecheckers Pyright and Mypy also do not do this, and there are no plans to support that type of refinement in Pyre.

For some reason the above comment reads like ChatGPT, but it's correct.

Something like this would work

```
from collections import abc
def filter_none(
    values: abc.Sequence[tuple[str, str | None]]
) -> abc.Iterable[tuple[str, str]]:
    return [(fst, snd) for fst, snd in values if snd is not None]
```

**Comment by eirnym** [comment]
I'm not opposed for a general lambda formatting, but I don't like to see the issue for standard functions like filter.

**Comment by yangdanny97** [comment]
It's not impossible to do, but this type of refinement would need to be special-cased in the typechecker (and the special-casing would need to be fairly complex). So it's more of a "how much work is this to add" v.s. "how common is this pattern/how big are the benefits" tradeoff.
