### ISSUE TITLE
[Question] How do we get all the types like we did in flow

### ISSUE THREAD

**Issue by neomatrix369** [facebook/pyre-check#90]
In `flow` the below command would return a `json` with all the type information at the various positions in the source:
```
flow dump-types --pretty
```

How do we do that in `pyre-check`?

Do we have some more examples of the usage?

**Comment by sinancepel** [comment]
Hey @neomatrix369, I think that's a good feature request! We do not currently support dumping all the types for a files into a `json`. If you're hoping to use this information to debug, you can use `reveal_type()` for the expression you're interested in.

**Comment by neomatrix369** [comment]
Thanks for the response @sinancepel 

Any examples of how `reveal_type()` could be used? This would be slow I'm guessing if we have a big file and like flow is pyre-check constrained to one source file at a time?

**Comment by sinancepel** [comment]
This wouldn't dump all the types at once; I wasn't sure what your use case was. You can wrap an expression in your code with reveal_type() to show its' type, but this isn't ideal if you want all annotations at once.

**Comment by dark** [comment]
Hi @neomatrix369 , the latest release of Pyre includes a feature that might be similar to what you want. If you have a running pyre server, you can use the query interface (via "pyre-check query") to, well, perform some server queries. 

One of such queries is `types_in_file`, that dumps a JSON with type information. For example:
```
# pyre-check query "types_in_file('tests.py')" | jq '.response.types'
[...]
[
  {
    "location": {
      "path": "tests.py",
      "start": {
        "line": 17,
        "column": 11
      },
      "stop": {
        "line": 17,
        "column": 13
      }
    },
    "annotation": "typing.List[tests.MyClass]"
  },
  {
    "location": {
      "path": "tests.py",
      "start": {
        "line": 8,
        "column": 20
      },
      "stop": {
        "line": 8,
        "column": 21
      }
    },
    "annotation": "bool"
  },
  {
    "location": {
      "path": "tests.py",
      "start": {
        "line": 8,
        "column": 28
      },
      "stop": {
        "line": 8,
        "column": 35
      }
    },
    "annotation": "typing.Type[tests.MyClass]"
  },
]
```

**Comment by maldil** [comment]
@dark thank you so much for the grate news. I also need to have types of all the methods for my analysis. I am so glad to hear about your suggestion. However, I am not quite familiar with "pyre-check query" (I just started using pyre and I just went through the guide). Could you please describe (an example code) about sending queries to the watchman server(I assumed pyre server==watchman server)?

**Comment by dark** [comment]
@maldil The pyre server is not the watchman server. The pyre server is a persistent instance of pyre that keeps running in the background and re-analyzes sources as they change. It also answers to queries coming from the query command.

You can run a query by running the command `pyre-check query $QUERY` from the shell. We have not really documented the query interface quite yet, since we do not consider that interface to be stable yet. In the meantime, you can look at the [test file](https://github.com/facebook/pyre-check/blob/master/command/test/queryTest.ml) or at the [query implementation file](https://github.com/facebook/pyre-check/blob/master/command/queryCommand.ml) to get a sense of what's available.

**Comment by maldil** [comment]
This works for me. 
Since there is no description available for this, I am describing the steps that I followed below
1. install pyre
2. install watchman
3. run `pyre` (this will generate the data and store in the server)
4. quarry the result as below
5. install jq
`pyre query "types_in_file('tests.py')" | jq '.response.types'`
@dark please correct me if I am wrong.

**Comment by dark** [comment]
Please see https://github.com/facebook/pyre-check/issues/90#issuecomment-432790924 for a solution.
